version: 2
jobs:
  build:
    docker:
        - image: circleci/python:3.6.6-jessie
    resource_class: medium
    environment:
      KUBECONFIG: /home/circleci/.kube/config
      MLT_TEST_CLUSTER_ENV_FILE: /tmp/mlt_test_cluster
      # Since it's not safe to run more threads than the actual avaialbe cores,
      # specially with compute intensive tests like horovod this was reduced to 2
      MAX_NUMBER_OF_THREADS_E2E: 2
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Installing test/lint dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -yq --no-install-recommends --fix-missing \
                build-essential \
                curl \
                git \
                libffi-dev \
                libssl-dev \
                libxml2-dev \
                libxslt1-dev \
                make \
                python \
                python-dev \
                python-pip \
                python-setuptools \
                python3 \
                python3-dev \
                python3-pip \
                python3-setuptools \
                python3-wheel \
                tar \
                zlib1g-dev

            sudo python -m pip install -U pip
            sudo pip install tox

      - run:
          name: lint tests
          command: |
            make lint-all

      - run:
          name: Run unit tests
          command: |
            make -e test-all-circleci

      - run:
          name: Run make dist and test the wheels and versions
          command: |
            make dist
            LATEST_TAG=$(git describe --abbrev=0 --tags)
            DIFF=$(git diff $LATEST_TAG)
            if [[ -z "$DIFF" ]]; then
              SHORT_HASH=${LATEST_TAG#"v"}
            else
              SHORT_HASH=$(git rev-parse --short HEAD)
            fi
            MLT_DIST_WHEEL="mlt*${SHORT_HASH}*-py2.py3-none-any.whl"
            ls dist/${MLT_DIST_WHEEL}
            if [[ $? != 0 ]]; then
                exit 1
            fi
            PIP=/usr/local/bin/pip
            sudo $PIP install -I dist/${MLT_DIST_WHEEL}
            PIP_DEPS=$(${PIP} freeze)
            if [[ $PIP_DEPS != *"mlt=="*"${SHORT_HASH}"* ]]; then
                exit 1
            fi
            . .venv/bin/activate
            MLT_VERSION=$(mlt --version)
            if [[ $MLT_VERSION != *"${SHORT_HASH}"* ]]; then
                exit 1
            fi
            deactivate

      - setup_remote_docker:
          docker_layer_caching: true
          version: 17.06.0-ce

      - run:
          name: Install gcloud
          command: |
            GCLOUD_SDK_VERSION="210.0.0"
            curl -sSLo google-cloud-sdk.tar.gz https://storage.googleapis.com/cloud-sdk-release/google-cloud-sdk-${GCLOUD_SDK_VERSION}-linux-x86_64.tar.gz \
            && tar zxf google-cloud-sdk.tar.gz \
            && rm google-cloud-sdk.tar.gz \
            && ./google-cloud-sdk/install.sh --usage-reporting=true --path-update=true
            ./google-cloud-sdk/bin/gcloud components install beta --quiet
            sudo apt-get install -y apt-transport-https
            curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            sudo sh -c 'echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list'
            sudo apt-get update
            sudo apt-get install -y kubectl

      - run:
          name: Create test cluster
          command: |
            export MLT_TEST_CLUSTER="mlt-test-cluster$CIRCLE_BUILD_NUM"
            echo $GKE_CREDENTIALS | base64 -di > mltkey.json
            ./google-cloud-sdk/bin/gcloud auth activate-service-account mltjson@intelai-mlt.iam.gserviceaccount.com --key-file=mltkey.json
            ./google-cloud-sdk/bin/gcloud --project intelai-mlt beta container clusters create "$MLT_TEST_CLUSTER" \
            --zone "us-west1-b" --cluster-version "1.10" --num-nodes "3" --machine-type "n1-highmem-4"
            sudo apt-get install -y kubectl
            ./google-cloud-sdk/bin/gcloud --project intelai-mlt beta container clusters get-credentials "$MLT_TEST_CLUSTER" \
            --zone "us-west1-b"

      - run:
          name: Set clusterrolebinding for kubeflow install later
          command: |
            # since running on a cluster with RBAC enabled, need workaround
            # https://github.com/kubeflow/kubeflow/blob/master/user_guide.md#rbac-clusters
            kubectl create clusterrolebinding default-admin --clusterrole=cluster-admin --user=mltjson@intelai-mlt.iam.gserviceaccount.com

      - run:
          name: Install ksync on cluster
          command: |
            # Please refer to https://github.com/vapor-ware/ksync for manual installation
            # user needs privs to do this on cluster so doing this here as well
            ./scripts/ksync_install.sh

      - run:
          name: Run e2e tests
          command: |
            make -e test-e2e-all-circleci
          # The timeout was increased to 30 due to new tensorflow images that require longer build times
          no_output_timeout: 30m

      - run:
          name: cleanup cluster
          when: always
          command: |
            export MLT_TEST_CLUSTER="mlt-test-cluster$CIRCLE_BUILD_NUM"
            ./google-cloud-sdk/bin/gcloud beta container clusters delete "$MLT_TEST_CLUSTER" --zone "us-west1-b" --project "intelai-mlt" --quiet
